#FROM php:8.1.8

FROM webdevops/php-nginx:8.1-alpine

RUN apk --no-cache add $PHPIZE_DEPS libstdc++ zlib-dev linux-headers\
    && CPPFLAGS="-Wno-maybe-uninitialized" MAKEFLAGS="-j $(nproc)" pecl install grpc-1.44.0 \
    && strip --strip-debug /usr/local/lib/php/extensions/*/grpc.so \
    && echo extension=grpc.so >> $PHP_INI_DIR/conf.d/docker-php-ext-grpc.ini

ENV WEB_DOCUMENT_ROOT="/app"
ENV WEB_DOCUMENT_INDEX="/public/index.php"
ENV COMPOSER_VERSION="1"