version: '3'

services:
  symfonydocker:
    container_name: symfony
    image: symfony
    build: 
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    ports:
      - 8000:80
    volumes:
      - ./app:/app
  database:
    #ulogiraj se u firebase svaki put kad se builda 
    container_name: firebase
    image: firebase
    build:
      dockerfile: Dockerfile.firestore
    ports:
      - 4000:4000
      - 8081:8081
    volumes:
      - ./app:/app
    environment:
      - giftcard
      - 1//09ByBWr9rIfQaCgYIARAAGAkSNwF-L9IrEAs8OEx_Y_WD-7GFhJqwdFl8XGh6tw92Xmz3ZcvdSj_otct98xgHqrkeDkJFzHKpIi8
  

